Update mitmproxy config for Python2 compat
Error message was:

Error: mitmproxy requires Python 3.5 or above

Starting with version 1.0 released in 12/2016, mitmproxy no longer supports Python 2.

To install the latest version of mitmproxy using pip on Python 3, run:

pip uninstall mitmproxy

pip3 install mitmproxy

You can also use our standalone binaries that come with their own Python interpreter:

http://docs.mitmproxy.org/en/stable/install.html

To get rid of this message and use the last version of mitmproxy that supports Python 2, run:

pip install "mitmproxy==0.18.2"

Apologies for the inconvenience!