Requests_Exception: change to namespaced class
Includes:
* Moving the namespaced version of the class to the `src` directory.
* [Custom autoload] Adding the class to the `$deprecated_classes` array in the `WpOrg\Requests\Autoload` class.
* [Composer autoload] Adding the class to the `Deprecated.php` file.
* Updating all references to the class.